#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = waybar
exec-once = mako
exec-once = nm-applet & blueman-applet
exec-once = fcitx5 -d
exec-once = wl-paste --watch cliphist -max-items 25 store
exec-once = swaybg --image /home/jade/Pictures/1311862.jpeg --mode fill
exec-once = /home/jade/.config/hypr/scripts/swayidle.sh

