#####################
### CURSOR        ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#cursor
cursor {
    hide_on_key_press = true
  }
