###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = foot
# $fileManager = dolphin
$fileManager = thunar
# $menu = hyprlauncher
$menu = fuzzel

