##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful
windowrule {
    name = floating-default-size
    match:float = true
    rounding = 4
    border_size = 2
}

windowrule {
    name = browser-no-border
    match:class = ^((vivaldi-stable)|(google-chrome))$
    border_size = 0
}

windowrule {
    name = floating-windows-volumectrl
    match:class = org.pulseaudio.pavucontrol
    float = true
    size = 1920 1080
}

windowrule {
    name = floating-windows-thunar
    match:class = thunar
    match:title = ^((Rename)|(File\sOperation)).*$
    float = true
}

windowrule {
    name = floating-windows-xdg
    match:class = xdg-desktop-portal-gtk
    match:title = ^((Open File)|(All Files)).*$

    float = true
    size = 1920 1080
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

